### ISSUE TITLE
weird-looking visual effect under nav bars

### ISSUE THREAD

**Issue by fredzannarbor** [TangleSpace/hydralit#11]
There's a weird-looking transition effect occurring underneath the nav bar.  I have the following values set:

[theme]
base="light"
primaryColor="#B21030"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#ceb829"

<img width="392" alt="Screen Shot 2021-09-26 at 12 50 10 AM" src="https://user-images.githubusercontent.com/1165771/134794220-6c1f9a05-99fe-43e0-8c5d-7cbc16855213.png">

Is this anything close to intentional?

**Comment by TangleSpace** [comment]
I'd recommend updating Hydralit and Hydralit_components, I've tightened up the animation on the navbar and added a new parameter so you can disable the animation. I'd recommend giving the new versions a go.
