### ISSUE TITLE
page state?

### ISSUE THREAD

**Issue by steeley** [TangleSpace/hydralit#14]
Does this support page state, so if you go to another page and comeback control values  in session.state  
are not reset.?
Couldn't see how to support this.

**Comment by TangleSpace** [comment]
This is actually partially available as of Streamlit version 1.3.1, the controls do remember their state (the data), but they don't remember their visual state usually, this is an issue with Streamlit itself and one they are unwilling to fix, as I've provided examples to them on issues relating this is and they for lack of better terms, don't give a shit and as of version 1.4.0 have broken Hydralit by completely altering the session state function. So for now, this is best to say not fully supported and dependant on how Streamlit feels at the time. 

The community deserves more than what Streamlit have been providing and I'm currently working on an extension to this project that will solve all these type of problems and more in one place.

**Comment by TangleSpace** [comment]
Thank you for your support.
