### ISSUE TITLE
Erros won't be displayed on app page

### ISSUE THREAD

**Issue by blimasouza** [TangleSpace/hydralit#15]
On version `hydralit==1.0.10`, when there is an error in the code, hydralit doens't have the default behaviour of streamlit of showing the error message on the page, instead it tries to show a failure image.

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/7920501/140773126-9e4ea6da-a967-4f74-bb9e-be7dcd31c093.png">

Is there a way to have the usual behaviour and simply show the error message?

**Comment by TangleSpace** [comment]
Thanks, there are some changes coming in the next version to allow more options with the errors, for now, if you create a folder called "resources" next to the file you are running and in that folder put any image you like, something small for example, https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/joypixels/291/cross-mark_274c.png
 and call it failure.png, you will see the true error details appear. 
![image](https://user-images.githubusercontent.com/50782232/140823706-76e9f922-e6be-4eae-8b5a-3f0f090d712f.png)

I've added this to the enhancement list. thanks

**Comment by TangleSpace** [comment]
I have pushed a new release with a fix for this issue, thank you very much for your support and hopefully you enjoy some of the other new features and fixes in this release.
