### ISSUE TITLE
show streamlit markers doesn't seem to work

### ISSUE THREAD

**Issue by fredzannarbor** [TangleSpace/hydralit#16]
In this toy application, i expect to see the Streamlit hamburger icon in the top right part of the page and the watermark at the bottom, but I don't.  

```
hydralit==1.0.10
hydralit-components==1.0.6
```

```
streamlit==1.1.0

```
```
import hydralit as hy

app = hy.HydraApp(title='Simple Multi-Page App', favicon="🐙",hide_streamlit_markers=False,use_navbar=True, navbar_sticky=True, use_banner_images="./resources/AI4booklovers.png")

@app.addapp()
def my_home():
 hy.info('Hello from app1')

@app.addapp()
def app2():
 hy.info('Hello from app 2')


#Run the whole lot, we get navbar, state management and app isolation, all with this tiny amount of work.
app.run()
```
<img width="1875" alt="Screen Shot 2021-11-11 at 2 06 14 PM" src="https://user-images.githubusercontent.com/1165771/141354676-66e13263-74fc-4814-86dd-922f4c7c3a2f.png">

**Comment by tiagolofi** [comment]
I have the same problem...

hydralit==1.0.10
hydralit-components==1.0.6

**Comment by TangleSpace** [comment]
Sorry for the late response and thank you for providing these details, I have found the issue and the next release will take care of this issue.

**Comment by TangleSpace** [comment]
I have pushed a new release with a fix for this issue, thank you very much for your support and hopefully you enjoy some of the other new features and fixes in this release.
