### ISSUE TITLE
thank you/small bug

### ISSUE THREAD

**Issue by rambam613** [TangleSpace/hydralit#17]
howdy, this is incredible work. I want to be you.

The loading_app in hydra_app points to a resources/failure.png file that comes with hydra-examples, but not with the module itself. It eclipses other error messages with "cant find failure.png". I think that line just needs to be wiped.

**Comment by TangleSpace** [comment]
Sorry for the late response and thank you for providing these details, I have found the issue and the next release will take care of this issue.

**Comment by rambam613** [comment]
youre a boss, love your work

**Comment by TangleSpace** [comment]
A very big thank you for finding and correcting this issue. I have pushed a new release with a fix derived from your solution, thank you very much for your support and hopefully you enjoy some of the other new features and fixes in this release.
