### ISSUE TITLE
Unable to redirect to Signup page

### ISSUE THREAD

**Issue by deeplearning987** [TangleSpace/hydralit#2]
Hello @TangleSpace 

We used secure hydra login for this entire process.

We added a new button Signup in Login Page.

We wanted to redirect to Signup Page from login page.

We are unable to redirect to signup page after clicking the signup button.

We are facing an issue.
![Screenshot (11)](https://user-images.githubusercontent.com/89828183/131666979-314de065-ec5a-4461-a6a7-6b1591d481f7.png)
![Screenshot (12)](https://user-images.githubusercontent.com/89828183/131666982-32f92c35-29d4-4a29-b473-debf124b73f3.png)

**Comment by deeplearning987** [comment]
Hello @TangleSpace any update ?

**Comment by TangleSpace** [comment]
This is not an issue, the ability to redirect to a signup page is able to be performed using access level checking or you could include the signup feature in the login app. Also, I'm not here to write your app, the framework works correctly and your inability to create the solution you want within the framework, is your issue, not an issue with the framework.
