### ISSUE TITLE
Does hydralit 1.0.11 require disk C access? 

### ISSUE THREAD

**Issue by raffieeey** [TangleSpace/hydralit#21]
First of all would like to thank you for hydralit, it makes building secure and multipage web app easy.

I have a question regarding the latest version of hydralit, when I run 

`easy_install "hydralit==1.0.11"`

I receive this error

> error: SandboxViolation: mkdir('C:\\Users\\XXXX\\.matplotlib', 511) {}
> 
> The package setup script has attempted to modify files on your system
> that are not within the EasyInstall build area, and has been aborted.
> 
> This package cannot be safely installed by EasyInstall, and may not
> support alternate installation locations even if you run its setup
> script by hand.  Please inform the package's author and the EasyInstall
> maintainers to find out if a fix or workaround is available. 

But when I run

`easy_install "hydralit==1.0.10"`

The installation runs successfully. Does the newest version require C disk access?

PS: I'm using `easy_install` instead of `pip` because I have some issues with my internet connection proxy

**Comment by TangleSpace** [comment]
Hi, thanks for the support, really appreciate it. Sadly, this was a bug, it doesn't require drive access more than any other package, there was an edge case with the installer that created this issue when install for the first time with Streamlit. A new release has been published that takes care of this issue and an accompanying new release of [Hydralit Components](https://github.com/TangleSpace/hydralit_components) has been published with 3 new components to help justify everyone's support for these packages. Should be fixed if you use the newest version 1.0.12. Thanks
