### ISSUE TITLE
st_ver variable in hydralit/sessionstate.py 

### ISSUE THREAD

**Issue by quentin-n-artefact** [TangleSpace/hydralit#22]
From last commit: `st_ver = 890` with streamlit version 0.8.9, which raises error

```bash
from streamlit.script_run_context import get_script_run_ctx
ModuleNotFoundError: No module named 'streamlit.script_run_context'
```
because streamlit version < 0.8.x go through `else:` statement :

```python
if st_ver < 140:
    import streamlit.report_thread as ReportThread
    from streamlit.server.server import Server
else:
    from streamlit.script_run_context import get_script_run_ctx
    from streamlit.server.server import Server
 ```

**Comment by TangleSpace** [comment]
Unfortunately it is reaching the point where Streamlit has mutated their API so far that I will need to revise the minimum version for the last couple of releases. I did test it with v1.x and all appeared fine. I would suggest that you update to a v1.x version and that should resolve the issue, I will add your feedback to the next release. Thanks
