### ISSUE TITLE
Change nav bar color

### ISSUE THREAD

**Issue by FernandoRocha88** [TangleSpace/hydralit#24]
First, thanks for the awesome job to create Hydralit, there is great synergy with Streamlit.

My question is quite not related to "technical aspects", but more to "design". How do I change the color of the navbar? Currently, it is red. I'd like to set my own, perhaps setting with color hex code.
Thanks a million!

**Comment by TangleSpace** [comment]
The reason it is red is the navbar picks up the theme colors from Streamlit. If you create a custom theme as per the Streamlit instructions [here](https://docs.streamlit.io/library/get-started/main-concepts#themes), the navbar will automatically changes colour.

If you want to change any of the colors on the navbar without changing the Streamlit theme colors, you can pass a dictionary that specifics exactly what color each part of the navbar should be, see the example below.

See the parameter: `navbar_theme`

```
#this is how to override any color in the navbar
over_theme = {'txc_inactive': 'purple','menu_background':'red','txc_active':'yellow','option_active':'blue'}

app = HydraApp(
        title='Secure Hydralit Data Explorer',
        favicon="🐙",
        use_navbar=True, 
        navbar_theme=over_theme,
)
```

Hope that helps.
