### ISSUE TITLE
How to change the default big loader?

### ISSUE THREAD

**Issue by DucoBouter** [TangleSpace/hydralit#26]
I'm making a streamlit app based on the hydralit-example: https://github.com/TangleSpace/hydralit-example

My app loads some data at first from database. While this is happening a rather large loading screen is present.
![image](https://user-images.githubusercontent.com/67575903/158220380-33e21684-a3a9-49e2-bd21-d6cdd9f53fbc.png)

How can I tame this loader and select a more compact one?

The structure of the code I use for the app-page:
import hydralit as hy
import pandas as pd
import streamlit as st

#create a wrapper class
class generate_app_page(hy.HydraHeadApp):
    def run(self):
        col1, col2 = hy.columns([2,4])
        msr = col1.selectbox('some nice label', get_ids_from_db())

**Comment by ryanblumenow** [comment]
You could try the solution recommended to me by the author in this: https://github.com/TangleSpace/hydralit/issues/23

**Comment by updaun** [comment]
/opt/conda/lib/python3.8/site-packages/hydralit/loading_app.py

![image](https://user-images.githubusercontent.com/82289435/170580102-44ee8604-3b80-4050-a9f2-c938f0aeb4f8.png)

you can change this line!

I finally found it.

**Comment by TangleSpace** [comment]
version 1.0.13 added the `use_loader=False` parameter so you can just by-pass the loader app entirely. if you want to create a completely custom app transition experience, just create a custom loader as per the details in the example repo.

https://github.com/TangleSpace/hydralit-example

![image](https://user-images.githubusercontent.com/50782232/174945922-1914c713-8a35-47b2-a18d-7653d40a70a2.png)
