### ISSUE TITLE
self.do_redirect does not change the menu option in the navbar

### ISSUE THREAD

**Issue by ryanblumenow** [TangleSpace/hydralit#29]
Hello @TangleSpace! I love this package!

I hope I am not doing something wrong, but when I put the code self.do_redirect("Title of app to run") in my code on a button, the relevant app does run, but the navbar does not change to reflect this. It stays on the navbar option of the original app where the button is housed.

Did I miss something, or do something incorrectly?

**Comment by ryanblumenow** [comment]
Hi there! Was just wondering if you could perhaps let me know what I've done wrong here?

**Comment by gamcoh** [comment]
Hi @ryanblumenow 

Did you find a fix?

**Comment by ryanblumenow** [comment]
Hi there. No not yet. Would love a fix for this.

**Comment by gamcoh** [comment]
Yes me too, I don't understand how we're supposed to do and why nobody else has this issue

**Comment by TangleSpace** [comment]
this has never worked and now Streamlit are creating their own version of multi-app support to suck more money out of the community, I won't be writing more code for them to rip off.
