### ISSUE TITLE
Issue facing while trying to add Signup App

### ISSUE THREAD

**Issue by deeplearning987** [TangleSpace/hydralit#3]
Hello @TangleSpace 

We followed the steps similar to login app and home app both are working fine and we also wanted to add extra feature like signup app.But we faced issue for redirecting the signup and we're struck at that place.

Signup app is working fine individually, like inserting details of user into database while calling the file individually. But when we're trying to call through a button click but instead of going to signup page we're redirecting to blank page.

We added

In hydra_app.py file we mentioned is_signup=False

def add_app(self, title, app, icon=None, is_login=False, is_signup=False is_home=False, logout_label=None):

For the Hydralit Framework there's no specific documentation. If there's any possibility to share the documentation please keep it.

**Comment by TangleSpace** [comment]
Added as a feature request.

**Comment by fredzannarbor** [comment]
Hi, I need this too, it is on my critical path.  @deeplearning987 if you can share your code for the signup app that would be a great help to me...

**Comment by TangleSpace** [comment]
I suggest you study the source code in the readme and the new code within the example secure app, with the addition of a new a parameter and a signup app in the example code.

https://github.com/TangleSpace/hydralit-example

#we have added a sign-up app to demonstrate the ability to run an unsecure app
#only 1 unsecure app is allowed
app.add_app("Signup", icon="🛰️", app=apps.SignUpApp(title='Signup'), is_unsecure=True)
