### ISSUE TITLE
No module 'streamlit.script_run_context'

### ISSUE THREAD

**Issue by ryanblumenow** [TangleSpace/hydralit#31]
Hi there. I am running Streamlit 1.8.1 (the latest, I think). When I try and run my Hydralit app, I get the following:

ModuleNotFoundError: No module named 'streamlit.script_run_context'

This seems to be part of the sessionstate.py file.

Can something be done to fix this on my side?

**Comment by Patarimi** [comment]
If I understand it correctly, streamlit change its API from time to time and it breaks everything. I made a fix, but it's not merge yet.
You can use my fork in the meantime.
with pip :
`pip uninstall hydralit`
`pip install git+https://github.com/Patarimi/hydralit.git`
If you use poetry or a requirements file, you can change `hydralit` with `git+https://github.com/Patarimi/hydralit.git`

**Comment by pedrostrusso** [comment]
@Patarimi the fix worked for me, thanks. Any idea when it will be merged?

**Comment by Patarimi** [comment]
I'm glad it works!
Only the owner of the repo can make the merge. So, I have no idea when it will be done.

**Comment by mwiertz** [comment]
@Patarimi thanks for your fix, it seems to work at first (and saved me a lot of time!). 

But as soon as I try to run the 'Lightning Example from [https://github.com/TangleSpace/hydralit](https://github.com/TangleSpace/hydralit), I get the following error:

```
Traceback (most recent call last):
  File "/.../app.py", line 3, in <module>
    app = hy.HydraApp(title='Simple Multi-Page App')

File "/.../.venv/lib/python3.8/site-packages/hydralit/hydra_app.py", line 184, in __init__
    self.session_state = SessionState.get(previous_app=None, selected_app=None,other_nav_app=None, preserve_state=preserve_state, allow_access=self._no_access_level,logged_in=False,access_hash=None)

File "/.../.venv/lib/python3.8/site-packages/hydralit/sessionstate.py", line 70, in get
    session_id = get_script_run_ctx().session_id

AttributeError: 'NoneType' object has no attribute 'session_id'
```

Haven't yet figured out how to fix it... Happy to hear if anyone already was able to get things running!

**Comment by jakecrowley** [comment]
@mwiertz That happens when you try to run the script directly, I believe. Try running it with `streamlit run`.

**Comment by chraibi** [comment]
> I'm glad it works! Only the owner of the repo can make the merge. So, I have no idea when it will be done.

@Patarimi 
That works for me too. Thanks. Hope this gets merged soon!

**Comment by TangleSpace** [comment]
New version 1.0.13 release now supports Streamlit >=1.9, until Streamlit decide to change more shit and break Hydralit again.
