### ISSUE TITLE
Set menu_items from page config

### ISSUE THREAD

**Issue by ryanblumenow** [TangleSpace/hydralit#33]
Hi there!

Is there a way to change the menu_items option (usually set in st.set_page_config) using Hydralit/the class Hydrapp? How would I specify these using Hydralit?

**Comment by TangleSpace** [comment]
if you just want to set the menu options, just use the navbar component, https://github.com/TangleSpace/hydralit_components

The menu is automatically built to support the apps you provide, if you want more options on the menu, add more apps, study the home page example and the example repo to see how to use the complex menu formatting.

https://github.com/TangleSpace/hydralit-example
