### ISSUE TITLE
Demo on Heroku is down

### ISSUE THREAD

**Issue by chraibi** [TangleSpace/hydralit#34]
This demo 
https://hydralit-secure-sample.herokuapp.com/ 
is not up and running. Maybe you have a link to the streamlit-cloud?

<img width="454" alt="Screen Shot 2022-05-11 at 19 38 34" src="https://user-images.githubusercontent.com/5772973/167912381-b2f6e82e-95da-42f5-b59a-73b1f168fe84.png">

**Comment by TangleSpace** [comment]
yes it is, the code for it is still available: https://github.com/TangleSpace/hydralit-example
