### ISSUE TITLE
hydralit 1.0.12 and streamlit 1.9.0

### ISSUE THREAD

**Issue by maxkryschi** [TangleSpace/hydralit#36]
Hi !

When I try to implement hydralit 1.0.12 in my App  (I use streamlit 1.9.0) the following error occurs:

 ```
from streamlit.script_run_context import get_script_run_ctx
ModuleNotFoundError: No module named 'streamlit.script_run_context'
```

It would be great if you could fix this. Thank you for sharing hydralit with us! :)

**Comment by quillaur** [comment]
Same bug for me.

**Comment by tjefferies** [comment]
Same bug for me, I think 4fd90e807a0da1c4e95b6bd31f1b15f4204a3918 fixes, @TangleSpace can you upload the version with this commit to PyPi ?

**Comment by pedrostrusso** [comment]
Also waiting for the update with the fix

**Comment by AravindRK99** [comment]
You can include streamlit.scriptrunner.script_run_context in the streamlit package. That should resolve the issue.

**Comment by TangleSpace** [comment]
New version 1.0.13 release now supports Streamlit >=1.9, until Streamlit decide to change more shit and break Hydralit again.
