### ISSUE TITLE
How to disable the (huge) "Now Loading YOUR.APP"

### ISSUE THREAD

**Issue by S-UP** [TangleSpace/hydralit#37]
We are exploring Hydralit.

One thing we do not quite appreciate is the huge "Now Loading YOUR.APP" notification when a page is starting up. We have not found in the docs the proper way to disable these.

Any suggestion?

**Comment by TangleSpace** [comment]
version 1.0.13 added the use_loader=False parameter so you can just by-pass the loader app entirely. if you want to create a completely custom app transition experience, just create a custom loader as per the details in the example repo.

https://github.com/TangleSpace/hydralit-example
