### ISSUE TITLE
allow more than 1 insecure app

### ISSUE THREAD

**Issue by fredzannarbor** [TangleSpace/hydralit#4]
Hello, is there some extremely important reason why there has to be a hard limit of 1 insecure app? In my use case I probably want to have several insecure apps that provide frictionless access to documentation and public data v. several secure ones with premium data.

**Comment by TangleSpace** [comment]
Security is about minimum surface area. You've completely missed the point in having access levels in the authentication process then. In the example app there two versions of the same app (Walsh & Walsh Secure), one requires level = 1 access, in this case that is the level provided by simply logging, the second version requires level = 2 access and can only be accessed if the user has level =2 (check the code, it's actually access_level > 1) assigned to their login details, see code here: https://github.com/TangleSpace/hydralit-example/blob/main/apps/walsh_app_secure.py#:~:text=access_level%2Cusername%20%3D%20self,if%20access_level%20%3E%201%3A

The ability to secure an app with authentication and then by-passing it by creating a set of apps that don't require any authentication is circular. You can do exactly your use case by checking access levels both within the app itself (the app handles if the user is allowed to run in, see the example, but still appears on the menu) and/or you can check the access level from the parent HydraApp (secure_app.py) and control what items appear to the user on the menu(navbar) so they can't even get to an app the aren't allowed to run (premium content), based on their access level, again, checking what they are allowed to see and adding/removing items that are to be displayed on the main menu(navbar). for example, if I didn't want to even show the secure Walsh app on the menu if the user is access_level =1, i put a check in the parent HydraApp (secure_app.py) (as it has access to the user authentication details) and add/remove it from the menu using the code below.

    #check user access level to determine what should be shown on the menu
    user_access_level = int(app.session_state.allow_access)

    if user_access_level > 1:
        complex_nav = {
            'Intro 🏆': ['Cheat Sheet',"Solar Mach"],
            'Hotstepper 🔥': ["Sequency Denoising","Sequency (Secure)"],
            'Clustering': ["Uber Pickups"],
            'NLP': ["Spacy NLP"],
        }
    elif user_access_level == 1:
        complex_nav = {
            'Intro 🏆': ['Cheat Sheet',"Solar Mach"],
            'Hotstepper 🔥': ["Sequency Denoising"],
            'Clustering': ["Uber Pickups"],
            'NLP': ["Spacy NLP"],
        }
    else:
        complex_nav = {
            'Home': ['Home'],
        }

Replace the existing definition of the complex_nav variable in the project example code with the above, with no other modification, the menu will change what is displayed based on the selected access level of the user, which you can set in a database or however you want, the example project is just that, you fill in the gaps with your specific details. 

Why I only allow one non_secure app, simple, you shouldn't need more than that if you are using the access level properties as they are meant to be used. If you want it to be open to job public without login but then have premium content that requires authentication, you should look at starting the app with an access level of 1 assigned in the parent with a dummy account (guest) and then lock away your premium apps using the techniques above with access level checking for the app to run and what is visible on the menu. For example, in the parent app (secure_app.py), add this above the complex_nav definition above,

    #just by-pass the login and set everything as level =1 access and the user as 'guest', for example.
    #the guest can't access level = 2 apps nor can they even see them on the menu, if they hit the logout button
    #they will drop to the login screen, put a button there to auto login back in as guest or get them to signup
    #or whatever you want

    #check if this is first open
    if app.session_state.allow_access == 0 and not hasattr(app.session_state,'current_user'):
        app.session_state.allow_access = 1
        app.session_state.current_user = 'guest'

this will log a 'guest' user in with level = 1 access without even showing the login app, but it is still a secure app, it has just logged them in as a guest with level 1 access. This is why you don't need more than 1 unsecure app, as that's just a way to completely lose control over all access within a secure app, if you want that, don't specify a login app and leave it completely open access.

**Comment by fredzannarbor** [comment]
That makes perfect sense -- the guest approach I mean.  Thanks for
explaining!
---
