### ISSUE TITLE
How to make navbar full-length of screen and placed all the way at the top?

### ISSUE THREAD

**Issue by tdtreece** [TangleSpace/hydralit#41]
Is there a way to have the built-in navbar using the HydraApp extend the full-length of the screen and bet stuck to the very top?

**Comment by TangleSpace** [comment]
Streamlit have messed with their component formatting, so the best the nav bar can do is allow room for the sidebar flip out bottom, making an even margin on the opposite side and a small gap at the top using the `hide_streamlit_markers=True`. Anything more, talk to Streamlit, as the $800M company doesn't need anymore of my free code to provide functionality they are looking to replace.
