### ISSUE TITLE
type objct 'Server' has not attribute 'get_current'

### ISSUE THREAD

**Issue by wraza2k9** [TangleSpace/hydralit#42]
Error Trace:

File "/home/ali/miniconda3/envs/streamlit-app/lib/python3.10/site-packages/hydralit/hydra_app.py", line 155, in __init__
    self.session_state = SessionState.get(previous_app=None, selected_app=None,other_nav_app=None, preserve_state=preserve_state, allow_access=self._no_access_level,logged_in=False,access_hash=None)
File "/home/ali/miniconda3/envs/streamlit-app/lib/python3.10/site-packages/hydralit/sessionstate.py", line 76, in get
    session_info = Server.get_current()._get_session_info(session_id)

**Comment by jayaranah** [comment]
this is removed in streamlit 1.12+
https://discuss.streamlit.io/t/accessing-session-info-in-1-12/29267

**Comment by TangleSpace** [comment]
please update to the latest package (1.0.14), as a fix has been created and deployed.

pip install -U hydralit

Thanks very much for your hard work saikumarmk!
