### ISSUE TITLE
Error when running app.run()

### ISSUE THREAD

**Issue by Unicorn7141** [TangleSpace/hydralit#46]
I've tried running my website and I have encountered the following error: `ModuleNotFoundError: No module named 'streamlit.scriptrunner'`

Here's my code if you wanna try and replicate it 
```py
import hydralit as hy

if __name__ == '__main__':
    app = hy.HydraApp(
        title="Trivia App",
        hide_streamlit_markers=True,
    )

    app.run()
```

**Comment by TangleSpace** [comment]
please update to the latest package (1.0.14), as a fix has been created and deployed.
